stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - docker

  before_script:
    - docker login nexus.cicd.internal:5000 -u $NEXUS_USER -p $NEXUS_PASSWORD

  script:
    - echo "Running Docker Build .."

    - docker pull node:13.12.0-alpine

    - docker images

    - ls -lrt 

    - pwd 

    - which docker 

    - hostname 

    - docker build -t $NEXUS_URL/$APP_IMAGE_NAME:$APP_IMAGE_VER .

    - docker images

    - docker push $NEXUS_URL/$APP_IMAGE_NAME:$APP_IMAGE_VER



